PreCommit:
  RuboCop:
    enabled: true
    description: "Ejecutando RuboCop para comprobar estilo de código"
    required_executable: 'rubocop'
    command: ['bundle', 'exec', 'rubocop']
    problem_on_unmodified_line: report
    on_warn: warn
    on_fail: fail
    include:
      - '**/*.rb'
    exclude:
      - 'app/assets/**/*'
      - 'app/views/**/*'
      - 'db/**/*.rb'
      - 'lib/**/*.rake'
      - 'config/**/*.rb'
      - 'bin/bundle'