name: RuboCop

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.3.4

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: RuboCop
      run: bundle exec rubocop --format json --out rubocop.json

    - name: Run reviewdog
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: 'latest'
        level: 'warning'
        reporter: 'github-check'
        fail_on_error: 'true'
        filter_mode: 'file'
        rubocop_flags: '--config .rubocop.yml'
        github_token: ${{ secrets.GITHUB_TOKEN }}